vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        pastes:
            uri_prefix: /images/pastes
            upload_destination: '%kernel.project_dir%/public/images/pastes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true